[package]
name = 'artichoke_ffi'
version = '0.1.0'
authors = ['Bruno Tavares <connect+github@bltavares.com>']
edition = '2018'

[lib]
crate_type = ['cdylib']

[dependencies]
libc = '0.2.76'

[dependencies.artichoke]
path = '..'
default-features = false
