[package]
name = "artichoke"
version = "0.1.0"
authors = ["Bruno Tavares <bruno.exz@gmail.com>"]

[dependencies.kuchiki]
git = "https://github.com/SimonSapin/kuchiki.git"

[[bin]]
doc = false
name = "artichoke"
